import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "test lwt",
  description: "Generated by create next app",
};

/* eslint-disable */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">{children}</body>
      {/* 用了 next/script + beforeInteractive 也没能实现提前挂载啊= = */}
      {/* <script src="https://code.jquery.com/jquery-3.7.1.js"></script> */}
      {/* <Script
        strategy="beforeInteractive"
        src="https://code.jquery.com/jquery-3.7.1.js"
      ></Script> */}
    </html>
  );
}
